# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='album_logo',
            field=models.FileField(upload_to=b''),
        ),
    ]
