# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0004_auto_20171114_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, upload_to=b'profile_image'),
        ),
    ]
