# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fac', '0006_auto_20171115_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSC', models.CharField(default=b'', max_length=100)),
                ('Intermediate', models.CharField(default=b'', max_length=100)),
                ('Btech', models.CharField(default=b'', max_length=100)),
                ('Mtech', models.CharField(default=b'', max_length=100)),
                ('PHD', models.CharField(default=b'', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='name',
            new_name='Faculty_name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='webmail',
        ),
        migrations.AddField(
            model_name='faculty',
            name='About',
            field=models.CharField(default=b'', max_length=2000),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Room_No',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Webmail',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='fax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
