# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0009_auto_20171115_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='Faculty_name',
            new_name='Faculty_Name',
        ),
    ]
