# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0010_auto_20171115_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Room_No',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
