# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0011_auto_20171115_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Position',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
