# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0012_faculty_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Webmail',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
