# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0013_auto_20171117_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Sponsorer',
            new_name='title',
        ),
    ]
