# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0015_auto_20171117_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Publications',
            new_name='Sponsorer',
        ),
        migrations.AddField(
            model_name='projects',
            name='role',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='teaching',
            name='Course_name',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
