# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0017_auto_20171117_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaching',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='year',
        ),
        migrations.AddField(
            model_name='projects',
            name='duration',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.DeleteModel(
            name='Teaching',
        ),
    ]
