# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0022_auto_20171118_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.FileField(default=b'media/profile_image/1.jpg', upload_to=b'media/profile_image'),
        ),
    ]
