# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0026_auto_20171118_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='Experience',
        ),
    ]
