# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0032_auto_20171122_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='Position',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Sponsorer',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='role',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Btech',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Mtech',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='PHD',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='Semester',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='time',
            field=models.CharField(default=b'', max_length=2000),
        ),
    ]
