# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0033_auto_20171128_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='Faculty_Name',
        ),
    ]
