# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0034_remove_faculty_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
