# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0035_auto_20171129_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fax',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
