# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 00:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fac', '0036_auto_20171129_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(default=b'', max_length=2000)),
                ('ans', models.CharField(default=b'', max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.FileField(default=b'project/media/profile_image/1.png', upload_to=b'project/media/profile_image/'),
        ),
    ]
