# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0037_auto_20171130_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default=b'Anonymous', max_length=2000),
        ),
    ]
