# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0039_auto_20171129_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(default=b'Unknown', max_length=2000),
        ),
    ]
